---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.vue"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
exclude_paths:
- dist/
- sashimi-webapp/static/vendors

