language: node_js
node_js:
  - "6"
env:
  - NODE_ENV=testing TEST_DIR=sashimi-webapp
  - NODE_ENV=testing TEST_DIR=sashimi-platform
script: cd $TEST_DIR && yarn && yarn test-travis
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < sashimi-webapp/test/unit/coverage/lcov.info
